# Generated by Django 2.0.4 on 2019-02-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cmname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('cimage', models.ImageField(upload_to='')),
                ('cuimage', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Moviee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mimage', models.ImageField(upload_to='')),
                ('uimage', models.FileField(blank=True, null=True, upload_to='')),
                ('movietime', models.CharField(max_length=50)),
                ('mtype', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('maincast', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
    ]
