# Generated by Django 2.0.4 on 2019-02-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviee',
            name='mimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
