# Generated by Django 2.0.4 on 2019-02-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0002_auto_20190213_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cuimage',
        ),
        migrations.RemoveField(
            model_name='moviee',
            name='uimage',
        ),
        migrations.AddField(
            model_name='cast',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviee',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviee',
            name='mimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
