# Generated by Django 2.0.4 on 2019-02-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0003_auto_20190213_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviee',
            name='mimage',
        ),
    ]
