# Generated by Django 2.0.4 on 2019-02-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0004_remove_moviee_mimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cimage',
        ),
    ]
