# Generated by Django 2.0.4 on 2019-02-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0006_auto_20190213_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='url',
            new_name='murl',
        ),
        migrations.RenameField(
            model_name='moviee',
            old_name='url',
            new_name='murl',
        ),
    ]
