# Generated by Django 2.0.4 on 2019-02-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0007_auto_20190213_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=100)),
                ('Revenue', models.CharField(max_length=100)),
                ('Production_Companies', models.CharField(max_length=150)),
                ('Production_Country', models.CharField(max_length=150)),
                ('adult', models.CharField(max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee')),
            ],
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='question',
            new_name='name',
        ),
    ]
