# Generated by Django 2.0.4 on 2019-02-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0008_auto_20190214_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviee',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
