# Generated by Django 2.0.4 on 2019-02-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0009_moviee_youtube'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Detai',
        ),
    ]
