# Generated by Django 2.0.4 on 2019-02-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0011_auto_20190214_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
        migrations.AlterField(
            model_name='detai',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
    ]
