# Generated by Django 2.0.4 on 2019-02-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0012_auto_20190214_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviee',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='detai',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
    ]
