# Generated by Django 2.0.4 on 2019-02-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0013_auto_20190214_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviee',
            options={},
        ),
    ]
