# Generated by Django 2.0.4 on 2019-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0014_auto_20190214_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviee',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
