# Generated by Django 2.0.4 on 2019-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0019_auto_20190220_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviee',
            name='maincast',
            field=models.TextField(),
        ),
    ]
