# Generated by Django 2.0.4 on 2019-02-23 19:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0020_auto_20190221_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviee',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='moviee',
            name='maincast',
            field=tinymce.models.HTMLField(),
        ),
    ]
