# Generated by Django 2.0.4 on 2019-02-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0022_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended',
            name='name',
        ),
        migrations.AlterField(
            model_name='detai',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rmovie.Moviee'),
        ),
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
