# Generated by Django 2.0.4 on 2019-02-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0023_auto_20190223_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detai',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rmovie.Moviee'),
        ),
    ]
