# Generated by Django 2.0.4 on 2019-02-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0025_auto_20190223_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlink', models.URLField(default='https://openloadmovies.net/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='rmovie.Moviee')),
            ],
        ),
        migrations.AlterField(
            model_name='detai',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
    ]
