# Generated by Django 2.0.4 on 2019-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0028_auto_20190224_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviee',
            name='quality',
            field=models.CharField(default='HD', max_length=100),
        ),
    ]
