# Generated by Django 2.0.4 on 2019-02-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0029_auto_20190224_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='mlink',
            field=models.URLField(blank=True, default='https://openloadmovies.net/', null=True),
        ),
    ]
