# Generated by Django 2.0.4 on 2019-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0030_auto_20190224_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielink',
            name='role',
            field=models.CharField(default='Rajmovie', max_length=50),
        ),
    ]
