# Generated by Django 2.0.4 on 2019-02-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0031_movielink_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lurl', models.URLField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='rmovie.Moviee')),
            ],
        ),
        migrations.RemoveField(
            model_name='movielink',
            name='name',
        ),
        migrations.DeleteModel(
            name='MovieLink',
        ),
    ]
