# Generated by Django 2.0.4 on 2019-02-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0032_auto_20190224_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='rmovie.Moviee'),
        ),
    ]
