# Generated by Django 2.0.4 on 2019-02-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0033_auto_20190224_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lurl',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rmovie.Moviee'),
        ),
    ]
