# Generated by Django 2.0.4 on 2019-02-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0034_auto_20190224_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
