# Generated by Django 2.0.4 on 2019-02-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0038_auto_20190224_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(default='http://www.watchonlinemovies.com.pk/'),
        ),
    ]
